baseURL = 'https://ribeyedundee.github.io/findtheobject/'
languageCode = 'en-us'
title = '🔎 Find the Object'
theme = 'ananke'
enableEmoji = true
Paginate = 10
publishDir = 'docs'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

