baseURL = 'https://ribeyedundee.github.io/findtheobject/'
languageCode = 'en-us'
title = 'Find the Object'
enableEmoji = true
publishDir = 'docs'
buildFuture = false

[markup]
  [markup.goldmark]
    renderer.unsafe = true

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[params]
  [params.blog]
    [params.blog.list]
      displayTags = true
  [params.toc]
    displayTags = true

